### ISSUE TITLE
FETCHOMMAND change

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [vaeth/trickyfetch#1]
I had to change `FETCHCOMMAND="trickyfetch \"\$URI\" \"\$DISTDIR\" \"\$FILE\""` to
`FETCHCOMMAND="trickyfetch \"\${URI}\" \"\${DISTDIR}\" \"\${FILE}\""` after portage complaining about missing `${FILE}`

**Comment by vaeth** [comment]
Thanks for reporting. README has been updated, and a new version has been released.
